apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
  namespace: argocd
spec:
  source:
    path: apps/gateway-service-umbrella-chart
    repoURL: https://github.com/AgusCarrizo94/gitops-demo
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.dev.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: governify
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
